### ISSUE TITLE
Minor speed improvement

### ISSUE THREAD

**Issue by da-anda** [liberty-developer/plugin.video.prime_instant#1]
From what I know, Kodi will always parse the default py file of an add-on (in this case default.py) and never cache it as pyo for faster processing. So I would suggest to only have the bare minimum in default.py and move the rest into another file that Kodi will then cache pre-parsed.

**Comment by liberty-developer** [comment]
thx, @da-anda. python is not my passion, for now I'm still waiting for anyone who cleans up this things. There are many codelines (e.g. primeproxy) wich can be removed completely.

Maybe if I have verrryyyy much time in the next few weeks I'll try a cleanup.
For me more the inputstream + decrypter is much more interesting.....
