### ISSUE TITLE
TV shows not showing episodes within season folders

### ISSUE THREAD

**Issue by cmgraz** [liberty-developer/plugin.video.prime_instant#11]
It appears a change to the Amazon API has rendered the tv section broken.

The issue was discussed here on the Kodi forums:
https://forum.kodi.tv/showthread.php?tid=298462&pid=2648446#pid2648446

![hdtveiz](https://user-images.githubusercontent.com/25110468/30571448-cde11ca8-9cb5-11e7-9292-4f82ce24501b.jpg)

**Comment by HoLiuS85** [comment]
I can confirm this issue in different testbuilds for x86_64 and RaspberryPi. As it happens on at least 4 different builds, the assumption that the API changed seems to be valid.

**Comment by liberty-developer** [comment]
should be fixed...
