### ISSUE TITLE
can see the catalog but can not play content.

### ISSUE THREAD

**Issue by bill-orange** [liberty-developer/plugin.video.prime_instant#6]
I suspect that I am doing something obvious wrong.  I ran

curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash

and loaded the app from the zip fine successfully.  I entered my Amazon Prime credentials without issue but I get this error.

19:25:40.585 T:1961328640 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:25:40.600 T:1528619936  NOTICE: Creating InputStream
19:25:41.038 T:1528619936   ERROR: AddOnLog: InputStream Adaptive: Unable to handle decryption. Unsupported!
19:25:41.038 T:1528619936   ERROR: CVideoPlayer::OpenInputStream - error opening 

What could I have missed!

**Comment by louisefindlay23** [comment]
I have the same problem too. How do you see what errors you get though? I only see check the log file.

**Comment by liberty-developer** [comment]
You have to install widevine shared library, pls. google for inputstream.adaptive and widevine.
